### ISSUE TITLE
cosine Distance

### ISSUE THREAD

**Issue by godofdream** [SthPhoenix/elastik-nearest-neighbors-extended#1]
I'm curious about the cosine distance implementation. 
What need's to be changed on the hashing part?

(I found a cosine implementation without touching the hashing)
https://github.com/jainaayush05/elastik-nearest-neighbors/commit/34984bc7aef67e21c348f601006b4f5fe998a228

**Comment by SthPhoenix** [comment]
Just switching to cosine metric at scoring step might work, but AFAIK most LSH implementations are optimized either for cosine or euclidean distance.
I have cosine metric for scoring in my local repo too, but haven't managed to measure recall yet, so it's not uploaded here as untested.

**Comment by SthPhoenix** [comment]
Update: cosine distance seems to work well with this LSH  implementation.

**Comment by SthPhoenix** [comment]
Closing, cosine distance already implemented
