### ISSUE TITLE
Error. When i try index element

### ISSUE THREAD

**Issue by arpsyapathy** [SthPhoenix/elastik-nearest-neighbors-extended#3]
Hello!

**I create index with:**
```
POST http://localhost:9200/_aknn_create/
{
    "_index":   "aknn_models",
    "_type":    "aknn_model",
    "_id":      "twitter_image_search",
    "_source": {
        "_aknn_description": "LSH model for Twitter image similarity search",
        "_aknn_nb_tables": 1,
        "_aknn_nb_bits_per_table": 1,
        "_aknn_nb_dimensions": 3
    },
    "_aknn_vector_sample": [
        [0.11, 0.22, 0.11],
        [0.22, 0.33, 0.22]
    ]
}
```

**than i try to index element:**
```
POST http://localhost:9200/_aknn_index
{
    "_index":       "twitter_images",
    "_type":        "twitter_image",
    "_aknn_uri":    "aknn_models/aknn_model/twitter_image_search",
    "_aknn_docs": [
        {
            "_id": 1,
            "_source":	{
                "_aknn_vector": [0.12, 0.23, 1.22]
            }
        }
    ]
}
```

End i get error:
```
{
    "error": {
        "root_cause": [
            {
                "type": "class_cast_exception",
                "reason": "class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')"
            }
        ],
        "type": "class_cast_exception",
        "reason": "class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')"
    },
    "status": 500
}
```

What i do wrong? thank you advance

**Comment by SthPhoenix** [comment]
Hi! Example you provided seems to be valid in terms of syntax, I'll try to check it later.
First of all check your mapping for index `twitter_images`,  it might be for some reason that  it has string type for field `_aknn_vector`.
If you'll check [batch_es_aknn_index.py](elastik-nearest-neighbors/demo/pipeline/batch_es_aknn_index.py) in original demo, you'll notice, that you need to create following mapping for index `twitter_images`:
```
mapping = {
        "properties": {
            "_aknn_vector": {
                "type": "half_float",
                "index": False
            }
        }
    }
```

Also I hope you're just testing, since config you used for model makes no sense.

**Comment by arpsyapathy** [comment]
@SthPhoenix 

Thank you for your reply!
What i do:

**1. I create LSH** 
```
POST http://localhost:9200/_aknn_create
{
        "_index": "aknn_models",
        "_type": "aknn_model",
        "_id": "twitter_images",
        "_source": {
	        "_aknn_description": "LSH model for Twitter image similarity search",
	        "_aknn_nb_tables": 1,
	        "_aknn_nb_bits_per_table": 1,
	        "_aknn_nb_dimensions": 3
        },
        "_aknn_vector_sample": [
	        [0.11, 0.22, 0.11],
	        [0.22, 0.33, 0.22]
        ]
}
```

**2.  I create index**
```
PUT http://localhost:9200/twitter_images
Result:
{
    "acknowledged": true,
    "shards_acknowledged": true,
    "index": "twitter_images"
}
```

**3. Create mapping for this index:**
```
PUT http://localhost:9200/twitter_images/twitter_image/_mapping
{
        "properties": {
            "_aknn_vector": {
                "type": "half_float",
                "index": false
            }
        }
}

Result:
{
    "acknowledged": true
}
```

**4. Post 2 vectors to index:**
POST http://localhost:9200/_aknn_index
1.
```
{
        "_index": "twitter_images",
        "_type": "twitter_image",
        "_aknn_uri": "aknn_models/aknn_model/twitter_images",
        "_aknn_docs": [
            {
                "_id": "1",
                "_source": {
                   "_aknn_vector": [0.24, 0.21, 0.28]
               }
            }
        ]
}
```

2.
```
{
        "_index": "twitter_images",
        "_type": "twitter_image",
        "_aknn_uri": "aknn_models/aknn_model/twitter_images",
        "_aknn_docs": [
            {
                "_id": "2",
                "_source": {
                   "_aknn_vector": [0.14, 0.31, 0.78]
               }
            }
        ]
}
```

**5. I try search by vector:**
```
POST http://localhost:9200/_aknn_search_vec?rescore=true&debug=false&minimum_should_match=3&clear_cache=false
{
    "_index": "twitter_images",
    "_type": "twitter_image",
    "_aknn_uri": "aknn_models/aknn_model/twitter_images",
    "query_aknn": {
            "_aknn_vector": [0.24, 0.21, 0.28],
            "k1":1000,
            "k2":100
     }
}
```

**But result:**
```
{
    "took": 10,
    "timed_out": false,
    "hits": {
        "max_score": 0,
        "total": 0,
        "hits": []
    }
}
```

Why? Element with id 1 have vector [0.24, 0.21, 0.28]
But i don't have him in search result...

What i can do wrong? Thank you advance

**Comment by SthPhoenix** [comment]
In code you provided, you indexed vecs with model `twitter_images,` but trying to search with model  `twitter_images2`.

**Comment by arpsyapathy** [comment]
@SthPhoenix  Sorry, thats mistake in text.
I create 2 index: twitter_images and twitter_images2.
In both cases, the search results are empty


P.S. Fixed a mistake in the text

**Comment by arpsyapathy** [comment]
@SthPhoenix 
Any idea what I might do wrong? Can you show me your examples?

**Comment by SthPhoenix** [comment]
You left  `minimum_should_match=3` from example. It means how many hashes should match for hit to be returned, in your case you have only one hash per document, while requiring 3 hashes to match.
Number of hashes is set by `_aknn_nb_tables`  at model creation step.

**Comment by arpsyapathy** [comment]
@SthPhoenix 
Thank you! I get results!.
Sorry for the many questions) But I still have a two of questions

**1. I get results like this:**
```
{
    "took": <number of milliseconds>,
    "timed_out": false,
    "hits": {
        "max_score": 0,
        "total": <number of hits returned, up to k2>,
        "hits": [
            {
                "_id": "...",
                '_index': "twitter_images",
                "_score": <euclidean distance from query vector to this vector>,
                '_source': {
                    "param1": "value1",
                    "_aknn_vector": [0.12, 0.23, ...]
                }
            }, 
        ]
    }
}
```

When i search bu vector i can get a few result with same value of param1.
How filter this? I can get unique results by param1 in search?

**2. Did you test vector search on a large index like in the original example?**
`in the image similarity search engine, you can see that searches against an index of 6.7 million 1000-dimensional vectors rarely exceed 200 milliseconds.`
Have you tested a vector search on a large index greater than 1 million for example?
how long does the request take?

Thank you advanced

**Comment by SthPhoenix** [comment]
1. You can filter results by param1, so that you'll get only hits with exact param1 value. If you want to get one hit per param1 value, than you should do it in your application, or reshape your data in some way.
2. `_aknn_search_vec` endpoint works almost the same as original _aknn_search,  it adds small overhead for computing hashes, but it doesn't depend from index size.
